version: "3.7"
services:
  web-proxy:
    image: jwilder/nginx-proxy
    container_name: web-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
      - ./docker-compose/nginx:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker-compose/nginx/vhosts:/etc/nginx/vhost.d
      - ./:/usr/share/nginx/html
    networks:
      - loger
    depends_on:
      - nginx
  ssl-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ssl-companion
    restart: always
    volumes_from:
      - web-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker-compose/nginx:/etc/nginx/certs:rw
    depends_on:
      - web-proxy
  nginx:
    image: nginx:alpine
    container_name: web-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/vhosts:/etc/nginx/conf.d/
      - ./:/usr/share/nginx/html
    environment:
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=${VIRTUAL_APP_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_APP_HOST}
      - LETSENCRYPT_EMAIL=jesusant.guerrero@gmail.com
    networks:
      - loger
  web:
    build:
      args:
        user: 'loger'
        uid: 1000
        TZ: America\New_York
      context: ./
      dockerfile: Dockerfile
    image: loger
    container_name: loger-app
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./:/var/www
      - loger_db:/var/lib/mysql
    networks:
      - loger
  landing:
    build:
      context: ecosystem/landing
      dockerfile: Dockerfile
    image: loger-landing
    container_name: loger-landing
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=${VIRTUAL_LANDING_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_LANDING_HOST}
      - LETSENCRYPT_EMAIL=jesusant.guerrero@gmail.com
    networks:
      - loger
  db:
    image: mysql:5.7
    container_name: loger-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - loger_db:/var/lib/mysql
      - ./docker-compose/mysql:/home/root/cache/
    networks:
      - loger
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - ./docker-compose/redis:/data
    networks:
      - loger
  cron:
    build:
      context: .
      dockerfile: cron.dockerfile
    container_name: cron
    volumes:
      - ./:/var/www
    working_dir: /var/www
    depends_on:
      - web
    networks:
      - loger
  phpmyadmin:
    depends_on:
      - db
    #links:
      #- db:mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    expose:
      - "8002"
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - VIRTUAL_HOST=phpmyadmin.${HOST_DOMAIN}
      #- VIRTUAL_PORT=8002
      - LETSENCRYPT_HOST=phpmyadmin.${HOST_DOMAIN}
      - LETSENCRYPT_EMAIL=jesusant.guerrero@gmail.com
networks:
  loger:
    driver: bridge
volumes:
  loger_db:
    driver: local
