services:
  web:
    build:
      args:
        uid: 1000
        TZ: America\New_York
      context: ./
      dockerfile: coolify.Dockerfile
    image: loger
    container_name: loger-app
    restart: unless-stopped
    volumes:
      - ./:/app
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      "8888:80"
    environment:
        DEBUG: "debug"
        # Change the following value if you know how it works.
        # MERCURE_TRANSPORT_URL: "bolt://mercure.db"
        MERCURE_PUBLISHER_JWT_KEY: "${MERCURE_PUBLISHER_JWT_KEY}"
        MERCURE_SUBSCRIBER_JWT_KEY: "${MERCURE_SUBSCRIBER_JWT_KEY}"
