services:
  loger:
    build:
      args:
        uid: 1000
        TZ: America\New_York
      context: ./
      dockerfile: coolify.Dockerfile
    image: loger
    container_name: loger-app
    restart: unless-stopped
    volumes:
      - ./storage:/var/www/storage
    environment:
        DEBUG: "debug"
        # Change the following value if you know how it works.
        # MERCURE_TRANSPORT_URL: "bolt://mercure.db"
        MERCURE_PUBLISHER_JWT_KEY: "${MERCURE_PUBLISHER_JWT_KEY}"
        MERCURE_SUBSCRIBER_JWT_KEY: "${MERCURE_SUBSCRIBER_JWT_KEY}"
        # In the cors_origin, add your domain(s). Or just use *
        MERCURE_EXTRA_DIRECTIVES: |-
            cors_origins "*"
            anonymous
        NODE_ENV: production
        VIRTUAL_PORT: 8000
        VIRTUAL_HOST: ${VIRTUAL_LANDING_HOST}
        LETSENCRYPT_HOST: ${VIRTUAL_LANDING_HOST}
        LETSENCRYPT_EMAIL: jesusant.guerrero@gmail.com
    env_file:
      - .env

