services:
  nginx:
    image: nginx:alpine
    container_name: loger-nginx
    restart: unless-stopped
    ports:
      - 8088:80
    depends_on:
      - web
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/vhosts:/etc/nginx/conf.d/
      - ./:/usr/share/nginx/html
    environment:
      - VIRTUAL_PORT=8088
      - VIRTUAL_HOST=${VIRTUAL_APP_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_APP_HOST}
      - LETSENCRYPT_EMAIL=jesusant.guerrero@gmail.com
  web:
    build:
      args:
        uid: 1000
        TZ: America\New_York
      context: ./
      dockerfile: coolify.Dockerfile
    image: loger
    container_name: loger-app
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker-compose/web/timezone:/etc/timezone
      - ./storage:/var/www/storage
      - /var/www/public/build
    env_file:
      - .env
