name: Loger Demo Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.composer/cache/files
        key: php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: bcmath, ctype, dom, fileinfo, intl, gd, json, mbstring, pdo, pdo_sqlite, openssl, sqlite, xml, zip

    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.testing.example', '.env');"

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Install Composer
      run: composer test

    - name: Build fronted
      uses: actions/setup-node@v4
      with:
        node-version: 20
      env:
        APP_URL: ${{ secrets.DO_APP_URL }}
        ASSET_URL: ${{ secrets.DO_APP_URL }}
        APP_DEMO: true
        VITE_APP_DEMO: true

    - run: yarn; yarn build

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: frontend-build
        path: |
          public/build
          public/manifest.json

    # - name: Execute tests (Unit and Feature tests) via PHPUnit
    #   env:
    #     DB_CONNECTION: sqlite
    #     DB_DATABASE: database/database.sqlite
    #   run: php artisan test

